name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/images/logo.png
  - lib/assets/images/personagem.png
